"""Create price tables

Revision ID: 5c37d0058858
Revises:
Create Date: 2021-11-07 22:15:52.135377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5c37d0058858"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "priceday", "time", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.drop_column("priceday", "id")
    op.alter_column(
        "priceminute", "time", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.drop_column("priceminute", "id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "priceminute", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.alter_column(
        "priceminute", "time", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.add_column(
        "priceday", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.alter_column(
        "priceday", "time", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###
